import { Value } from '@mxfriend/oscom';
import { FxType } from '../enums';
import {
  AmbienceParams,
  ChamberParams, ChorusChamberParams,
  ChorusParams,
  CombinatorParams,
  DelayChamberParams,
  DelayChorusParams,
  DelayFlangerParams,
  DimensionalChorusParams,
  DualDeEsserParams,
  DualEnhancerParams,
  DualPitchParams,
  EdisonEX1Params,
  ExciterParams,
  FairCompParams,
  FlangerChamberParams,
  FlangerParams,
  FourTapDelayParams,
  GatedReverbParams,
  GeqParams,
  GuitarAmpParams, HallParams,
  LeisureCompParams,
  ModulationDelayParams,
  MoodFilterParams,
  MSFairCompParams,
  PhaserParams,
  PlateParams,
  PrecisionLimiterParams,
  ReverseReverbParams,
  RichPlateParams,
  RoomParams,
  RotarySpeakerParams,
  SoundMaxerParams,
  StereoDeEsserParams,
  StereoDelayParams,
  StereoEnhancerParams,
  StereoImagerParams,
  StereoPitchParams,
  SuboctaverParams,
  ThreeTapDelayParams,
  TremoloPannerParams,
  TubeStageParams,
  UltimoCompParams,
  VintageReverbParams,
  VintageRoomParams,
  WaveDesignerParams,
  Xtec1AParams, XtecQ5Params,
} from './effects';
import { FxParamList } from './fxParamList';

export type FxParamListConstructor = {
  new (): FxParamList;
};

function Dual(ctor: FxParamListConstructor, n: number): FxParamListConstructor {
  const max = 2 * n;

  return class extends ctor {
    protected $createParam(param: number): Value {
      return super.$createParam(param >= n && param < max ? param % n : param);
    }
  }
}

export const paramListMap: Record<FxType, FxParamListConstructor> = {
  [FxType.Hall]: HallParams,
  [FxType.Ambience]: AmbienceParams,
  [FxType.RichPlate]: RichPlateParams,
  [FxType.Room]: RoomParams,
  [FxType.Chamber]: ChamberParams,
  [FxType.Plate]: PlateParams,
  [FxType.VintageReverb]: VintageReverbParams,
  [FxType.VintageRoom]: VintageRoomParams,
  [FxType.GatedReverb]: GatedReverbParams,
  [FxType.ReverseReverb]: ReverseReverbParams,
  [FxType.StereoDelay]: StereoDelayParams,
  [FxType.ThreeTapDelay]: ThreeTapDelayParams,
  [FxType.FourTapDelay]: FourTapDelayParams,
  [FxType.Chorus]: ChorusParams,
  [FxType.Flanger]: FlangerParams,
  [FxType.Phaser]: PhaserParams,
  [FxType.DimensionalChorus]: DimensionalChorusParams,
  [FxType.MoodFilter]: MoodFilterParams,
  [FxType.RotarySpeaker]: RotarySpeakerParams,
  [FxType.TremoloPanner]: TremoloPannerParams,
  [FxType.Suboctaver]: SuboctaverParams,
  [FxType.DelayChamber]: DelayChamberParams,
  [FxType.ChorusChamber]: ChorusChamberParams,
  [FxType.FlangerChamber]: FlangerChamberParams,
  [FxType.DelayChorus]: DelayChorusParams,
  [FxType.DelayFlanger]: DelayFlangerParams,
  [FxType.ModulationDelay]: ModulationDelayParams,
  [FxType.DualGEQ]: Dual(GeqParams, 32),
  [FxType.StereoGEQ]: GeqParams,
  [FxType.DualTEQ]: Dual(GeqParams, 32),
  [FxType.StereoTEQ]: GeqParams,
  [FxType.DualDeEsser]: DualDeEsserParams,
  [FxType.StereoDeEsser]: StereoDeEsserParams,
  [FxType.StereoXtec1A]: Xtec1AParams,
  [FxType.DualXtec1A]: Dual(Xtec1AParams, 11),
  [FxType.StereoXtecQ5]: XtecQ5Params,
  [FxType.DualXtecQ5]: Dual(XtecQ5Params, 9),
  [FxType.WaveDesigner]: WaveDesignerParams,
  [FxType.PrecisionLimiter]: PrecisionLimiterParams,
  [FxType.StereoCombinator]: CombinatorParams,
  [FxType.DualCombinator]: Dual(CombinatorParams, 29),
  [FxType.StereoFairComp]: FairCompParams,
  [FxType.MidSideFairComp]: MSFairCompParams,
  [FxType.DualFairComp]: Dual(FairCompParams, 7),
  [FxType.StereoLeisureComp]: LeisureCompParams,
  [FxType.DualLeisureComp]: Dual(LeisureCompParams, 5),
  [FxType.StereoUltimoComp]: UltimoCompParams,
  [FxType.DualUltimoComp]: Dual(UltimoCompParams, 6),
  [FxType.DualEnhancer]: DualEnhancerParams,
  [FxType.StereoEnhancer]: StereoEnhancerParams,
  [FxType.DualExciter]: Dual(ExciterParams, 7),
  [FxType.StereoExciter]: ExciterParams,
  [FxType.StereoImager]: StereoImagerParams,
  [FxType.EdisonEX1]: EdisonEX1Params,
  [FxType.SoundMaxer]: SoundMaxerParams,
  [FxType.DualGuitarAmp]: Dual(GuitarAmpParams, 9),
  [FxType.StereoGuitarAmp]: GuitarAmpParams,
  [FxType.DualTubeStage]: Dual(TubeStageParams, 10),
  [FxType.StereoTubeStage]: TubeStageParams,
  [FxType.DualPitch]: DualPitchParams,
  [FxType.StereoPitch]: StereoPitchParams,
};
