import {
  Dual,
  DualDeEsserParams,
  DualEnhancerParams,
  EdisonEX1Params,
  ExciterParams,
  FairCompParams,
  FxParamListConstructor,
  GeqParams,
  GuitarAmpParams,
  LeisureCompParams,
  MoodFilterParams,
  MSFairCompParams,
  PhaserParams,
  PrecisionLimiterParams,
  SoundMaxerParams,
  StereoDeEsserParams,
  StereoEnhancerParams,
  StereoImagerParams,
  SuboctaverParams,
  TremoloPannerParams,
  TubeStageParams,
  UltimoCompParams,
  WaveDesignerParams,
  Xtec1AParams,
  XtecQ5Params,
} from '@mxfriend/common';
import { InsertFxType } from '../enums';

export const insertParamListMap: Record<InsertFxType, FxParamListConstructor> = {
  [InsertFxType.DualGEQ]: Dual(GeqParams, 32),
  [InsertFxType.StereoGEQ]: GeqParams,
  [InsertFxType.DualTEQ]: Dual(GeqParams, 32),
  [InsertFxType.StereoTEQ]: GeqParams,
  [InsertFxType.DualDeEsser]: DualDeEsserParams,
  [InsertFxType.StereoDeEsser]: StereoDeEsserParams,
  [InsertFxType.StereoXtec1A]: Xtec1AParams,
  [InsertFxType.DualXtec1A]: Dual(Xtec1AParams, 11),
  [InsertFxType.StereoXtecQ5]: XtecQ5Params,
  [InsertFxType.DualXtecQ5]: Dual(XtecQ5Params, 9),
  [InsertFxType.WaveDesigner]: WaveDesignerParams,
  [InsertFxType.PrecisionLimiter]: PrecisionLimiterParams,
  [InsertFxType.StereoFairComp]: FairCompParams,
  [InsertFxType.MidSideFairComp]: MSFairCompParams,
  [InsertFxType.DualFairComp]: Dual(FairCompParams, 7),
  [InsertFxType.StereoLeisureComp]: LeisureCompParams,
  [InsertFxType.DualLeisureComp]: Dual(LeisureCompParams, 5),
  [InsertFxType.StereoUltimoComp]: UltimoCompParams,
  [InsertFxType.DualUltimoComp]: Dual(UltimoCompParams, 6),
  [InsertFxType.DualEnhancer]: DualEnhancerParams,
  [InsertFxType.StereoEnhancer]: StereoEnhancerParams,
  [InsertFxType.DualExciter]: Dual(ExciterParams, 7),
  [InsertFxType.StereoExciter]: ExciterParams,
  [InsertFxType.StereoImager]: StereoImagerParams,
  [InsertFxType.EdisonEX1]: EdisonEX1Params,
  [InsertFxType.SoundMaxer]: SoundMaxerParams,
  [InsertFxType.DualGuitarAmp]: Dual(GuitarAmpParams, 9),
  [InsertFxType.StereoGuitarAmp]: GuitarAmpParams,
  [InsertFxType.DualTubeStage]: Dual(TubeStageParams, 10),
  [InsertFxType.StereoTubeStage]: TubeStageParams,
  [InsertFxType.Phaser]: PhaserParams,
  [InsertFxType.MoodFilter]: MoodFilterParams,
  [InsertFxType.TremoloPanner]: TremoloPannerParams,
  [InsertFxType.Suboctaver]: SuboctaverParams,
};
